### ISSUE TITLE
OBC emulator functionality and purpose

### ISSUE THREAD

**Issue by dmarszk** [PW-Sat2/PWSat2OBC#416]
Looking at the integration tests, I am wondering what is the exact functionality of the [emulator](
https://github.com/PW-Sat2/PWSat2OBC/tree/master/integration_tests/emulator)?
Could it be used as a standalone tool emulating rudimentary OBC TM/TC traffic of PW-Sat 2, or does it still require an additional hardware?
If yes, is there some document or piece of code/makefile that would be a good starting point?

**Comment by Novakov** [comment]
Emulator allows running OBC hardware (so yes, additional hadware is required) without "real" devices like EPS, COMM, etc. It was used during development of OBC software. It is composed of two parts: emulated devices (e.g. COMM module is described here: https://github.com/PW-Sat2/PWSat2OBC/blob/master/integration_tests/devices/eps.py) and user interface for controling these devices.

Regarding starting point it really depends on what your are looking for. For emulator/integration tests it's best to start from simple tests (`test_i2c.py` is quite simple yet showing few important components of test infrastructure). For OBC code it self I think you should start from `src\obc.h` as it contains (at some level) the most important parts of the software.

**Comment by dmarszk** [comment]
That clarifies it. Thanks for your answer!
